# -*- coding: utf-8 -*-
"""Probability and Statistics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxRg7JShV2PXKN-GOgyKn-Fo0gkLqrDT
"""

import pandas as pd

# Load the historical data
data = pd.read_csv('/content/Lottery_Mega_Millions_Winning_Numbers__Beginning_2002.csv')

# Process the data as needed
# For example, convert dates to datetime objects and extract winning numbers
# ...

# Calculate the frequency of each number being drawn
number_frequencies = data['Winning Numbers'].value_counts(normalize=True)

# Generate Predictions
next_prediction = number_frequencies.idxmax()
print("Predicted number:", next_prediction)

import pandas as pd
import matplotlib.pyplot as plt

# Load the historical data
data = pd.read_csv('/content/Lottery_Mega_Millions_Winning_Numbers__Beginning_2002.csv')

# Convert date column to datetime format
data['Draw Date'] = pd.to_datetime(data['Draw Date'])

# Extract winning numbers and year from the date
data['Year'] = data['Draw Date'].dt.year
data['Winning Numbers'] = data['Winning Numbers']  # Replace 'winning_number_column' with your column name

# Group data by year and analyze frequency trends over time
number_frequency_yearly = data.groupby(['Year', 'Winning Numbers']).size().unstack().fillna(0)

# Plotting frequency of each number over the years
plt.subplots(figsize=(12, 8))
number_frequency_yearly.plot(marker='o')
plt.title('Frequency of Winning Numbers Over Years')
plt.xlabel('Year')
plt.ylabel('Frequency')
plt.legend(title='Number', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.subplots_adjust(top=0.92, bottom=0.08, left=0.10, right=0.90, hspace=0.25, wspace=0.35)
# Adjust top, bottom, left, right, hspace, wspace to fit the plot
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load the historical data
data = pd.read_csv('/content/Lottery_Mega_Millions_Winning_Numbers__Beginning_2002.csv')

# Extract winning numbers column (replace 'winning_number_column' with your column name)
winning_numbers = data['Winning Numbers']

# Plotting histogram to visualize the distribution
plt.figure(figsize=(8, 6))
plt.hist(winning_numbers, bins=range(1, 51), alpha=0.7, edgecolor='black')
plt.title('Distribution of Winning Numbers')
plt.xlabel('Numbers')
plt.ylabel('Frequency')
plt.xticks(range(1, 51))  # Ensure x-axis ticks from 1 to 50 for lottery numbers
plt.grid(axis='y')  # Add gridlines on the y-axis
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the historical data
data = pd.read_csv('/content/Lottery_Mega_Millions_Winning_Numbers__Beginning_2002.csv')

# Extract the columns containing winning numbers (adjust columns as per your dataset)
winning_numbers = data[['Draw Date', 'Winning Numbers', 'Mega Ball', 'Multiplier']]

# Calculate the correlation matrix
correlation_matrix = winning_numbers.corr(numeric_only=True)

# Plotting the correlation matrix using a heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Pairwise Correlation of Winning Numbers')
plt.show()